version: "3.8"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data