version: "3.8"

networks:
  tld-challenges:
    external: true

services:
  db:
    container_name: tld-challenges-db
    image: tld-challenges-db:latest
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - tld-challenges
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s