version: "3.8"

networks:
  tld-challenges:
    external: true

services:
  db:
    container_name: tld-challenges-db
    image: tld-challenges-db:latest
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - tld-challenges